/** 各钻孔基本信息与柱状图分层（folder 对应模型目录） */
export const DRILL_HOLE_INFO = {
  out2: {
    id: "XSBYSZK01",
    mileageStake: "ZK82+876.5左54米",
    elevation: 859.36,
    coordX: 3242635.47,
    coordY: 504439.91,
    depth: 270.37,
    stableWaterLevel: 254.0,
    finalDiameter: 91,
    layers: [
      {
        sequence: 1,
        stratumCode: "Qel+dl（Q4）",
        lithology: "红黏土",
        from: 0,
        to: 6.2,
        thickness: 6.2,
        color: "#C05030",
        description:
          "黄褐色，可塑状，底部含灰岩块石，块径约20～30 cm。",
      },
      {
        sequence: 2,
        stratumCode: "T1j2",
        lithology: "灰岩",
        from: 6.2,
        to: 34.0,
        thickness: 27.8,
        color: "#D9D9D9",
        description:
          "灰色、微晶质结构，中厚层状构造，矿物成分主要为方解石，裂隙较发育，倾角以70°～80°为主，闭合，被方解石充填，岩芯多呈柱状、短柱状，部分长柱状、碎块状。",
      },
      {
        sequence: 3,
        mergeStratumCode: "T1j2",
        stratumCodeBreak: true,
        lithology: "溶洞",
        from: 34.0,
        to: 37.1,
        thickness: 3.1,
        color: "#4A90E2",
        description:
          "溶洞：有掉钻现象，溶洞内有碎石土充填，碎石直径1～5 mm，次棱角状。为灰岩及页岩碎石，含量约40%。",
      },
      {
        sequence: 4,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 37.1,
        to: 74.8,
        thickness: 37.7,
        color: "#D9D9D9",
        description:
          "灰色、灰黑色，微晶质结构，中厚层状构造，矿物主要成分为方解石，细方解石脉发育，部分含沥青质，呈灰黑色岩芯呈长柱状、柱状，部分碎块状。",
      },
      {
        sequence: 5,
        mergeStratumCode: "T1j2",
        lithology: "煤层",
        from: 74.8,
        to: 78.8,
        thickness: 4.0,
        color: "#000000",
        description:
          "煤，黑色；74.8～75.1 m丝绢光泽、污手；75.1～76.3 m为采空区，掉钻，推测为采空区；78.1～78.4 m为煤层，黑色，丝绢光泽，质轻。",
      },
      {
        sequence: 6,
        mergeStratumCode: "T1j2",
        lithology: "炭质页岩",
        from: 78.8,
        to: 102.0,
        thickness: 23.2,
        color: "#6B6B6B",
        description:
          "炭质页岩，灰黑色，泥质结构，厚层状构造，101.2～101.3 m夹薄层煤。岩芯呈长柱状、柱状，易风化裂解。",
      },
      {
        sequence: 7,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 102.0,
        to: 125.7,
        thickness: 23.7,
        color: "#D9D9D9",
        description:
          "灰岩，灰色、灰黑色，微晶质结构，中厚层状构造，局部方解石脉发育，缝合线构造发育，岩体较完整，岩芯多呈长柱状、柱状，少量碎块状、短柱状。",
      },
      {
        sequence: 8,
        mergeStratumCode: "T1j2",
        lithology: "页岩",
        from: 125.7,
        to: 138.3,
        thickness: 12.6,
        color: "#808080",
        description:
          "灰黑色，泥质结构，厚层状构造，页理发育，局部含碳质较重。133.7－135.0m 夹灰黑色灰岩。岩体完整呈长柱状，页岩岩质软，易风化裂解。",
      },
      {
        sequence: 9,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 138.3,
        to: 205.0,
        thickness: 66.7,
        color: "#D9D9D9",
        description:
          "灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈短柱状～柱状、碎块状，最大节长 40cm，岩质较硬，为中风化带。RQD=64.8%。162－164.0m 段为灰黑色灰岩夹页岩。181－189.3m 段为灰色和灰黑色灰岩夹页岩。199－200.5m 段为灰黑色灰岩夹页岩。",
      },
      {
        sequence: 10,
        mergeStratumCode: "T1j2",
        lithology: "角砾岩",
        from: 205.0,
        to: 213.4,
        thickness: 8.4,
        color: "#C49A6C",
        description:
          "角砾岩，灰黑色、灰色，角砾状构造，角砾母岩为灰岩，粒径2～20 cm，胶结一般，可击碎。岩芯呈碎块状、柱状，最大节长20 cm，RQD=33%。",
      },
      {
        sequence: 11,
        mergeStratumCode: "T1j2",
        lithology: "铝土岩",
        from: 213.4,
        to: 216.5,
        thickness: 3.1,
        color: "#A74E1F",
        description:
          "铝土岩，灰白色，泥质结构，薄层状构造，以粘土矿物为主，泥质胶结，岩芯呈短柱状，岩质软，易风化、易击碎，为中风化带。",
      },
      {
        sequence: 12,
        mergeStratumCode: "T1j2",
        lithology: "页岩",
        from: 216.5,
        to: 228.3,
        thickness: 11.8,
        color: "#808080",
        description:
          "页岩，灰黑色，泥质结构，薄层状构造，以黏土矿物组成，岩芯较完整。",
      },
      {
        sequence: 13,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 228.3,
        to: 250.47,
        thickness: 22.17,
        color: "#D9D9D9",
        description:
          "灰岩，灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈短柱状-柱状，碎块状，最大节长40cm，岩质较硬，为中风化带。",
      },
      {
        sequence: 14,
        mergeStratumCode: "T1j2",
        lithology: "采空区",
        from: 250.47,
        to: 255.17,
        thickness: 4.7,
        color: "#C0C0C0",
        description: "采空区：无充填，掉钻。",
      },
      {
        sequence: 15,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 255.17,
        to: 270.37,
        thickness: 15.2,
        color: "#D9D9D9",
        description:
          "灰岩，灰～灰白色，微晶质结构，中厚层状构造，主要由碳酸盐类矿物组成，岩芯较完整，节长5～30 cm。",
      },
    ],
  },
  out3: {
    id: "XSBYSZK02",
    mileageStake: "ZK83+211.6左68.8米",
    elevation: 939.2,
    coordX: 3242588.67,
    coordY: 504772.02,
    depth: 380.65,
    stableWaterLevel: 220.0,
    finalDiameter: 91,
    layers: [
      {
        sequence: 1,
        stratumCode: "Q4el+dl",
        lithology: "红黏土",
        from: 0,
        to: 1.2,
        thickness: 1.2,
        color: "#C05030",
        description:
          "黄色，可塑状，稍有光泽，无摇振反应，干强度及韧性中等。",
      },
      {
        sequence: 2,
        stratumCode: "T1j2",
        lithology: "灰岩",
        from: 1.2,
        to: 4.7,
        thickness: 3.5,
        color: "#D9D9D9",
        description: "灰色，岩芯呈柱状，溶蚀发育。",
      },
      {
        sequence: 3,
        mergeStratumCode: "T1j2",
        stratumCodeBreak: true,
        lithology: "溶洞",
        from: 4.7,
        to: 6.3,
        thickness: 1.6,
        color: "#4A90E2",
        description: "充填细砂。",
      },
      {
        sequence: 4,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 6.3,
        to: 12.3,
        thickness: 6.0,
        color: "#D9D9D9",
        description:
          "灰色，岩芯呈柱状、短柱状，溶蚀凹槽、孔洞发育。",
      },
      {
        sequence: 5,
        mergeStratumCode: "T1j2",
        lithology: "溶洞",
        from: 12.3,
        to: 14.9,
        thickness: 2.6,
        color: "#4A90E2",
        description: "溶洞内充填少量砂土。",
      },
      {
        sequence: 6,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 14.9,
        to: 18.0,
        thickness: 3.1,
        color: "#D9D9D9",
        description:
          "灰色，岩芯呈柱状、短柱状，溶蚀凹槽、孔洞发育。",
      },
      {
        sequence: 7,
        mergeStratumCode: "T1j2",
        lithology: "溶洞",
        from: 18.0,
        to: 20.7,
        thickness: 2.7,
        color: "#4A90E2",
        description: "溶洞充填细砂。",
      },
      {
        sequence: 8,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 20.7,
        to: 78.5,
        thickness: 57.8,
        color: "#D9D9D9",
        description:
          "灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈柱状，节长约8～55cm，岩质较硬，属中风化带,RQD约82%。",
      },
      {
        sequence: 9,
        mergeStratumCode: "T1j2",
        lithology: "溶洞",
        from: 78.5,
        to: 79.05,
        thickness: 0.55,
        color: "#4A90E2",
        description: "溶洞。",
      },
      {
        sequence: 10,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 79.05,
        to: 81.5,
        thickness: 2.45,
        color: "#D9D9D9",
        description:
          "灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈柱状,岩质较硬,为中分化带，RQD约23%",
      },
      {
        sequence: 11,
        mergeStratumCode: "T1j2",
        lithology: "溶洞",
        from: 81.5,
        to: 82.35,
        thickness: 0.85,
        color: "#4A90E2",
        description: "溶洞。",
      },
      {
        sequence: 12,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 82.35,
        to: 83.15,
        thickness: 0.8,
        color: "#D9D9D9",
        description:
          "灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈柱状,岩质较硬,为中分化带，RQD约23%",
      },
      {
        sequence: 13,
        mergeStratumCode: "T1j2",
        lithology: "溶洞",
        from: 83.15,
        to: 86.15,
        thickness: 3.0,
        color: "#4A90E2",
        description: "溶洞。",
      },
      {
        sequence: 14,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 86.15,
        to: 87.2,
        thickness: 1.05,
        color: "#D9D9D9",
        description:
          "灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈柱状,岩质较硬,为中分化带，RQD约23%",
      },
      {
        sequence: 15,
        mergeStratumCode: "T1j2",
        lithology: "溶洞",
        from: 87.2,
        to: 89.85,
        thickness: 2.65,
        color: "#4A90E2",
        description: "溶洞。",
      },
      {
        sequence: 16,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 89.85,
        to: 93.0,
        thickness: 3.15,
        color: "#D9D9D9",
        description:
          "灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈柱状,岩质较硬,为中分化带，RQD约23%。",
      },
      {
        sequence: 17,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 93.0,
        to: 140.0,
        thickness: 47.0,
        color: "#D9D9D9",
        description:
          "灰岩(夹煤线):灰黑色,微晶质结构,中厚层状构造,以碳酸盐类矿物为主,岩芯呈碎块状、短柱状、柱状,节长6-40cm,岩质较硬,为中风化带。该段岩芯有臭味。RQD=40%。98.8-99.30m、99.8-100.0m、102.8-103.0m、107.3-107.5m、114.3-114.5m、119.8m-121.0m、127.5-127.6m、129.0-132.4m、137.6-138.0m、139.6-139.9m段为灰岩夹薄层煤线。105-105.6m段为溶洞,111-113m段为溶隙,充填粘土。",
      },
      {
        sequence: 18,
        mergeStratumCode: "T1j2",
        lithology: "灰岩",
        from: 140.0,
        to: 380.65,
        thickness: 240.65,
        color: "#D9D9D9",
        description:
          "灰黑色夹灰色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯较完整，呈柱状，节长8-50cm，岩质较硬，为微风化带。RQD=92-95%。168.8-169.2m、172.3-172.7m、180.2-181.10m段夹薄层页岩。204-208m段为灰色夹灰白色，夹方解石脉。218-223m段夹灰白色方解石脉。283-315m段夹灰白色方解石条纹。346.9-347.5m段夹薄层炭质页岩。348-380.65m段夹灰白色方解石条纹。",
      },
    ],
  },
  out4: {
    id: "XSBYSZK03",
    mileageStake: "ZK85+733.7右68.8米",
    elevation: 1252.18,
    coordX: 3242040.11,
    coordY: 507235.37,
    depth: 625.4,
    stableWaterLevel: 160.4,
    finalDiameter: 91,
    layers: [
      {
        sequence: 1,
        stratumCode: "P3c",
        lithology: "砂质页岩",
        from: 0,
        to: 17.0,
        thickness: 17.0,
        color: "#B7B29A",
        description:
          "砂质页岩：灰黄色，泥质结构，细粒结构，薄层状构造，以粘土矿物为主，泥质胶结。岩芯破碎，呈碎块状、土状，风化裂隙发育，岩质软，为强风化带。局部见薄层状泥灰岩、灰岩。",
      },
      {
        sequence: 2,
        mergeStratumCode: "P3c",
        stratumCodeBreak: true,
        lithology: "灰岩",
        from: 17.0,
        to: 41.0,
        thickness: 24.0,
        color: "#D9D9D9",
        description:
          "灰岩：灰黑色，微晶质结构，以碳酸盐类矿物为主。岩芯呈短柱状、柱状，节长4-60cm，少许碎块状，RQD=88%，岩质较硬，为中风化带。底部31-41m段为角砾状灰岩，角砾粒径4-12cm，棱角状，胶结较好。",
      },
      {
        sequence: 3,
        mergeStratumCode: "P3c",
        lithology: "白云岩",
        from: 41.0,
        to: 47.9,
        thickness: 6.9,
        color: "#CFE2F3",
        description:
          "白云岩：浅灰色，白云质结构，微晶质结构，中厚层状构造，以白云石和碳酸盐类矿物为主。岩芯呈柱状、少许短柱状，节长15-68cm，岩质较硬，为中等风化带。RQD=94%。",
      },
      {
        sequence: 4,
        mergeStratumCode: "P3c",
        lithology: "灰岩",
        from: 47.9,
        to: 71.9,
        thickness: 24.0,
        color: "#D9D9D9",
        description:
          "灰岩：灰黑色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主。岩芯呈柱状，少许短柱状，为中等风化带。RQD=94%，65-71.9m段为灰色。",
      },
      {
        sequence: 5,
        mergeStratumCode: "P3c",
        lithology: "砂质页岩",
        from: 71.9,
        to: 78.3,
        thickness: 6.4,
        color: "#B7B29A",
        description:
          "砂质页岩：灰黑色，泥质结构，粉粒结构，薄层状构造，以粘土矿物、长石为主，泥钙质胶结。岩芯呈短柱状、柱状，节长4-21cm，RQD=60%，岩质较软，易击碎，属于中风化带，局部夹钙质结核。77.3-77.8m为采空区。",
      },
      {
        sequence: 6,
        mergeStratumCode: "P3c",
        lithology: "铝土岩",
        from: 78.3,
        to: 81.6,
        thickness: 3.3,
        color: "#A74E1F",
        description:
          "铝土岩：灰白色、白色，泥质结构，薄层状构造，以粘土矿物为主，岩芯呈短柱状-柱状，节长4-41cm，80.4-81.6m等多呈碎块状，少许短柱状，岩质较软，易开裂，为中风化带。RQD=40%，底部见铜矿，层中夹铜矿结核。",
      },
      {
        sequence: 7,
        mergeStratumCode: "P3c",
        lithology: "灰岩",
        from: 81.6,
        to: 376.8,
        thickness: 295.2,
        color: "#D9D9D9",
        description:
          "灰岩：灰黑色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主，岩芯呈柱状，少许短柱状，节长8—100cm。岩质较硬，为中等风化带。RQD=97%。100.5—118.0m段呈灰黑色，局部见灰白色方解石条纹。118—155.5m呈灰色，155.5—168m呈灰黑色；168—235m段主要呈灰色，局部夹灰黑色，局部为角砾状灰岩，角砾粒径1—8cm，呈棱角状，胶结较好。235—318m段主要呈灰黑色，局部段落呈灰色；318—324m段呈灰色，324—376.8m段呈灰黑色夹灰色。全段岩芯较完整，呈柱状，少许短柱状，节长8—100cm，RQD=95—98%。",
      },
      {
        sequence: 8,
        mergeStratumCode: "P3c",
        lithology: "灰岩",
        from: 376.8,
        to: 561.4,
        thickness: 184.6,
        color: "#D9D9D9",
        description:
          "灰岩：灰黑色，微晶质结构，中厚层状构造，以碳酸盐类矿物为主。岩芯较完整，呈柱状，少许短柱状，节长7—62cm，岩质较硬，为中等风化带。RQD=96%。377—377.6m、378.3—378.7m、384.8—385.9m、402.2—402.4m、404.9—405.5m、406.7—407.3m、407.6—408.4m、410—410.4m、421.7—422.3m、424.0—424.4m、427.7—427.9m段呈灰黑色，薄层状，为薄层灰岩夹薄层煤线，岩质软，易击碎，层面指甲可刻划，层面光滑。442—561.4m段呈灰色—灰白色。462.7m处见一倾角约70°的裂隙，面粗糙，无充填。469.8—471.0m含碳质较重。",
      },
      {
        sequence: 9,
        mergeStratumCode: "P3c",
        lithology: "页岩",
        from: 561.4,
        to: 582.4,
        thickness: 21.0,
        color: "#808080",
        description:
          "页岩：灰色-灰黑色，泥质结构，薄-中厚层状构造，主要由粘土矿物组成，岩芯完整，多呈长柱状，节长5-100cm，局部夹薄层灰岩。",
      },
      {
        sequence: 10,
        mergeStratumCode: "P3c",
        lithology: "煤",
        from: 582.4,
        to: 583.3,
        thickness: 0.9,
        color: "#000000",
        description: "煤层：黑色，丝绢光泽，质轻。",
      },
      {
        sequence: 11,
        mergeStratumCode: "P3c",
        lithology: "页岩",
        from: 583.3,
        to: 605.0,
        thickness: 21.7,
        color: "#808080",
        description:
          "页岩：灰色、灰白色，泥质结构，薄-中厚层状构造，主要由粘土矿物组成，岩芯完整，多呈长柱状，节长3-100cm，局部夹薄层灰岩。",
      },
      {
        sequence: 12,
        mergeStratumCode: "P3c",
        lithology: "页岩",
        from: 605.0,
        to: 625.4,
        thickness: 20.4,
        color: "#808080",
        description:
          "页岩：紫红色，泥质结构，中厚层状构造，主要由粘土矿物组成，岩芯完整，多呈长柱状，节长5-100cm。",
      },
    ],
  },
};

export function getDrillHoleInfo(folder) {
  return DRILL_HOLE_INFO[folder] ?? null;
}
